### ISSUE TITLE
Handshake failed

### ISSUE THREAD

**Issue by Lazarus404** [membraneframework/ex_dtls#30]
Getting an error;

    erlang 23.3
    elixir 1.14.0-otp-23

```
18:05:54.265 [error] GenServer #PID<0.344.0> terminating
** (RuntimeError) Handshake failed: no packets generated
    (unifex 1.1.0) lib/unifex/cnode.ex:122: Unifex.CNode.handle_response/1
    (ex_dtls 0.12.0) lib/ex_dtls.ex:367: ExDTLS.call/4
    (ex_dtls 0.12.0) lib/ex_dtls.ex:229: ExDTLS.handle_call/3
    (stdlib 3.14.1) gen_server.erl:715: :gen_server.try_handle_call/4
    (stdlib 3.14.1) gen_server.erl:744: :gen_server.handle_msg/6
    (stdlib 3.14.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.335.0>): :do_handshake
```

I thought at first that perhaps SSL wasn't installed, but it seems fine otherwise within Erlang. Not sure what else to check, here.

**Comment by Lazarus404** [comment]
Running the library as a NIF solves the issue.
